### ISSUE TITLE
Use control dial to toggle scenes?

### ISSUE THREAD

**Issue by joesanta** [XeroxDev/Loupedeck-plugin-NanoleafControl#1]
Great plugin. Is there a way you can add functionality so that we can use the dial to change scenes?

**Comment by chinyau** [comment]
I do not see any authenticate button after installing. any idea why?

**Comment by XeroxDev** [comment]
> Great plugin. Is there a way you can add functionality so that we can use the dial to change scenes?
- @joesanta 

Sorry for the late reply (for some reason I've overlooked this / wasn't on my radar)

But I looked into it and I don't think your suggestion is possible to add due to performance and the high possibility to break everything.

> I do not see any authenticate button after installing. any idea why?
- @chinyau

I don't think this is the right place to discuss this problem. Could you either create a own issue for it or join the Discord so we can discuss it?

As well. Is there a possibility that your computer and your devices aren't on the (exact) same network? Other users had the same problem if their devices where on a completly other network or on a sub network.

**Comment by XeroxDev** [comment]
Hey! Small note. The plugin got a new update!

But due to your request, I sadly have to deny it. Don't understand me wrong, it's a awesome request but for now I won't implement it and /close this issue.
